
from django.contrib import admin
from django.urls import path
from . import views
from . import cycleprocess,kdgriddml,wms,codepriv,sendsalary,uatwms
from django.urls import re_path
urlpatterns = [
    path('', views.index, name='index'),
    path('vkeepexcel', views.vkeepexcel,name='vkeepexcel'),
    path('handlevkeep', views.handlevkeep,name='handlevkeep'),
    # path('cyclesort', views.cyclesort,name='cyclesort'),
    path('handlecycle', views.handlecycle,name='handlecycle'),
    path('base_test', views.base_test,name='base_test'),
    path('cycles', views.cycles,name='cycles'),
    path('handlecrate', views.handlecrate,name='handlecrate'),
    path('crate', views.crate,name='crate'),
    # path('querycycle', views.querycycle,name='querycycle'),
    # path('getcycledata', views.getcycledata,name='getcycledata'),
    path('cyclesummary', cycleprocess.cyclesummary,name='cyclesummary'),
    path('handlecyclesummary', cycleprocess.handlecyclesummary,name='handlecyclesummary'),
    path('cycledetail', cycleprocess.cycledetail,name='cycledetail'),
    path('cyclebybarcode', cycleprocess.cyclebybarcode,name='cyclebybarcode'),
    path('handlecyclebarcode', cycleprocess.handlecyclebarcode,name='handlecyclebarcode'),
    path('vhrjoindate', views.vhrjoindate,name='vhrjoindate'),
    path('handlehrjoindate', views.handlehrjoindate,name='handlehrjoindate'),
    path('get_function_tree', views.get_function_tree,name='get_function_tree'), 
    path('index', views.index,name='index'), 
    path('signature', views.signature,name='signature'), 
    path('sendsalary', views.sendsalary,name='sendsalary'), 
    path('hangdlesalary', sendsalary.hangdlesalary,name='hangdlesalary'),
    path('sendtoeachuser', sendsalary.sendtoeachuser,name='sendtoeachuser'),
    path('celltype', wms.setcelltype,name='celltype'), 
    path('cellsource', wms.setcellsource,name='cellsource'), 
    path('stockin', wms.setstockin,name='stockin'), 
    path('stockin_form', wms.stockin_form,name='stockin_form'), 
    path('stockin_create', wms.stockin_create,name='stockin_create'), 
    path('stockin_cancel', wms.stockin_cancel,name='stockin_cancel'), 
    path('stockout', wms.setstockout,name='stockout'), 
    path('stockout_create', wms.stockout_create,name='stockout_create'), 
    path('stockout_cancel', wms.stockout_cancel,name='stockout_cancel'), 
    path('stockquery', wms.stockquery,name='stockquery'), 
    path('setresourcetype', codepriv.setresourcetype,name='setresourcetype'), 
    path('setresource', codepriv.setresource,name='setresource'), 
    path('resourcelisting', codepriv.resourcelisting,name='resourcelisting'), 
    path('coderead', codepriv.coderead,name='coderead'),     
    path('readresource', codepriv.readresource,name='readresource'), 
    path('uatcelltype', uatwms.setuatcelltype,name='uatcelltype'), 
    path('uatstockin', uatwms.setuatstockin,name='uatstockin'), 
    path('uatstockin_create', uatwms.uatstockin_create,name='uatstockin_create'), 
    path('uatstockin_cancel', uatwms.uatstockin_cancel,name='uatstockin_cancel'), 
    path('uatstockout', uatwms.setuatstockout,name='uatstockout'), 
    path('uatstockout_create', uatwms.uatstockout_create,name='uatstockout_create'), 
    path('uatstockout_cancel', uatwms.uatstockout_cancel,name='uatstockout_cancel'), 
    path('uatstockout_return', uatwms.uatstockout_return,name='uatstockout_return'), 
    path('uatstockout_memo', uatwms.uatstockout_memo,name='uatstockout_memo'), 
    path('uatstockquery', uatwms.uatstockquery,name='uatstockquery'), 
    path('getuatstockoutreturn', uatwms.getuatstockoutreturn,name='getuatstockoutreturn'), 
    re_path(r'^listing/(?P<model_name>[\w\-]+)$',
        kdgriddml.listing, name='listing'),
    re_path(r'^updatelist/(?P<model_name>[\w\-]+)$',
        kdgriddml.updatelist, name='updatelist'),
    re_path(r'^create/(?P<model_name>[\w\-]+)$',
        kdgriddml.createnew, name='createnew'),
    re_path(r'^delete/(?P<model_name>[\w\-]+)$',
        kdgriddml.deleteone, name='deleteone'),
]
